### ISSUE TITLE
the netcode fucking sucks

### ISSUE THREAD

**Issue by checkraisefold** [johnfortnitekennedy/JFKMarioWorld#3]
![JFKMarioWorld_0Eb5PVLFfx](https://user-images.githubusercontent.com/19525688/80567562-49926d00-89aa-11ea-8e70-25fa439403e6.png)

it appears that the netcode is fucking broken
its been 2 minutes and player position hasn't synced. also we had throwable blocks spawning mid air and just throwing for like a minute and a haslf straight for all clients
we dont want to become the guy in the picture
![2544323](https://user-images.githubusercontent.com/19525688/80567514-3384ac80-89aa-11ea-86a1-cacd83cb6910.png)

**Comment by johnfortnitekennedy** [comment]
https://www.youtube.com/watch?v=EloVyBMXVI0

**Comment by johnfortnitekennedy** [comment]
Is this it? This is what I got all those ass whoopings for? I had a dream once. It was a dream that little black boys and little black girls would drink from the river of prosperity, freed from the thirst of oppression. But lo and behold, some four decades later, what have I found but a bunch of trifling, shiftless, good-for-nothing niggas? And I know some of you don't want to hear me say that word. It's the ugliest word in the English language, but that's what I see now: niggas. And you don't want to be a nigga, 'cause niggas are living contradictions! Niggas are full of unfulfilled ambitions! Niggas wax and wane; niggas love to complain! Niggas love to hear themselves talk, but hate to explain! Niggas love being another man's judge and jury! Niggas procrastinate until it's time to worry! Niggas love to be late, niggas hate to hurry! Black Entertainment Television is the worst thing I've ever seen in my life! Usher, "Michael Jackson" is not a genre of music! And now I'd like to talk about Soul Plane. I've seen what's around the corner, I've seen what's over the horizon, and I promise you - you niggas won't have nothing to celebrate. And no, I won't get there with you. I'm going to Canada!

**Comment by checkraisefold** [comment]
LOL

**Comment by checkraisefold** [comment]
NO WAIT DELETE THAT THE PR IS GOING TO GET BANED BY GITHUB

**Comment by johnfortnitekennedy** [comment]
https://tenor.com/beimc.gif

**Comment by johnfortnitekennedy** [comment]
[https://tenor.com/beimc.gif ](url)

**Comment by johnfortnitekennedy** [comment]
wtf

**Comment by johnfortnitekennedy** [comment]
how do u embed images

**Comment by johnfortnitekennedy** [comment]
https://tenor.com/view/supermario-mariobros-supermarioworld-gif-6102932

**Comment by checkraisefold** [comment]
What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.

**Comment by johnfortnitekennedy** [comment]
Wen

**Comment by johnfortnitekennedy** [comment]
The funny hits just right

**Comment by johnfortnitekennedy** [comment]
Laughter track.wav plays

**Comment by johnfortnitekennedy** [comment]
I think that should be solved because noone found ur joke funny

**Comment by johnfortnitekennedy** [comment]
DAMN OOOOOOOOOHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by johnfortnitekennedy** [comment]
net sync can be made more stable by changing

network_update_rate = 8
packet_wait_time = 8

both of these to 64 instead of 8, though it doesnt work too well and lowers the receive rate (it'll look slower ingame like it's lower fps or something) though its a notable improvement so idk im closing this because this issue happens because theres too much being sent at once and that's the configs fault. it should have stayed at 16 lol

**Comment by johnfortnitekennedy** [comment]
maybe 32 is stable (32ms) but idk lol
