### ISSUE TITLE
fix socket spammer server DDoSing

### ISSUE THREAD

**Issue by johnfortnitekennedy** [johnfortnitekennedy/JFKMarioWorld#4]
theres been reports of apparently a socket spammer being released which crashes servers with a malformed packet which contains a player join data and the text "fuck jannies" repeated over and over, crashing the server, we need to implement some sort of sanitization to the packets to prevent this behaviour from happening. idk when will this happen tho

**Comment by checkraisefold** [comment]
WE CAN'T FIX IT ITS CODED IN GO BRO ITS TOO POWERFUL

**Comment by johnfortnitekennedy** [comment]
wrong just add a check that unpacks data thens like "if data == "fuck jannies" stop the packet lol ez

**Comment by checkraisefold** [comment]
appears to be patched after latest update, jfk is pushing to git

**Comment by checkraisefold** [comment]
may be fucked - plz wait

**Comment by checkraisefold** [comment]
nvm it works.... the army will figure out another way

**Comment by johnfortnitekennedy** [comment]
patched and probably will stay that way for a long time, security will also be reinforced when checking packets so

also shut the fuck up im not going to port the game to go retard
